# Generated by Django 5.1.15 on 2026-08-27 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streaming', '0002_alter_camera_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLMPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('prompt', models.TextField(verbose_name='完整 prompt')),
                ('positive_keyword', models.CharField(default='是', max_length=64, verbose_name='命中关键词')),
                ('image_filename_hint', models.CharField(default='拍摄时间', help_text='让 VLM 用文件名当时间参考的提示语', max_length=64, verbose_name='文件名提示')),
                ('result_format', models.CharField(default='plain', help_text='plain=纯文本命中关键词；json=预留', max_length=16, verbose_name='返回格式')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('manual_paused', models.BooleanField(default=False, verbose_name='手动暂停')),
                ('window_sec', models.IntegerField(default=10, help_text='v6 cursor 必需；范围 5~30', verbose_name='窗口秒数')),
                ('time_window_enabled', models.BooleanField(default=False, verbose_name='启用时段')),
                ('time_window_start', models.TimeField(blank=True, null=True, verbose_name='时段起点')),
                ('time_window_end', models.TimeField(blank=True, null=True, verbose_name='时段终点')),
                ('weekdays', models.CharField(default='1,2,3,4,5,6,7', help_text='1-7 逗号分隔；7=周日', max_length=32, verbose_name='星期')),
                ('timeout_sec_first', models.IntegerField(default=60, verbose_name='冷启 timeout(s)')),
                ('timeout_sec_normal', models.IntegerField(default=15, verbose_name='正常 timeout(s)')),
                ('silence_count_after_dismiss', models.IntegerField(default=5, help_text='用户标某条 (cam, prompt, status) 为误报后，连续 N 次同状态签名触发则静默。任一条件打破则静默失效：(a) status 变化；(b) 中间有空档不触发；(c) 连续静默次数达 N。', verbose_name='误报后静默次数')),
                ('notify_on_hit', models.BooleanField(default=True, verbose_name='命中时通知')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_ids', models.ManyToManyField(blank=True, help_text='限定生效摄像头；空 = 所有摄像头', related_name='prompt_configs', to='streaming.camera', verbose_name='限定摄像头')),
            ],
            options={
                'verbose_name': 'VLM 检查项',
                'verbose_name_plural': 'VLM 检查项',
                'db_table': 'vlm_prompt_config',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VLMCheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_list', models.JSONField(default=list, help_text='窗口内所有 ts（int 列表，按时间升序；window_start = ts_list[0]）', verbose_name='窗口 ts 列表')),
                ('window_sec', models.IntegerField(help_text='冗余便于查；= len(ts_list)', verbose_name='窗口长度')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('hit', models.BooleanField(verbose_name='是否命中')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='VLM 原始返回')),
                ('status', models.CharField(blank=True, default='', help_text='从 VLM 返回中提取的状态关键词；构成静默状态签名 (cam, prompt, status)', max_length=64, verbose_name='状态描述')),
                ('img1', models.CharField(blank=True, default='', max_length=512, verbose_name='最早帧路径')),
                ('img2', models.CharField(blank=True, default='', max_length=512, verbose_name='中间帧路径')),
                ('img3', models.CharField(blank=True, default='', max_length=512, verbose_name='最晚帧路径')),
                ('img1_ts', models.IntegerField(blank=True, null=True, verbose_name='最早帧 ts')),
                ('img2_ts', models.IntegerField(blank=True, null=True, verbose_name='中间帧 ts')),
                ('img3_ts', models.IntegerField(blank=True, null=True, verbose_name='最晚帧 ts')),
                ('has_baby_in_window', models.BooleanField(default=False, verbose_name='窗口内有 baby')),
                ('failure_reason', models.CharField(blank=True, choices=[('timeout', '超时'), ('network_error', '网络错误'), ('parse_error', '解析错误'), ('no_baby', '窗口内无 baby'), ('manual_paused', '已被手动暂停'), ('out_of_window', '窗口已被 FrameQueue 淘汰')], default='', help_text='VLM 调用失败原因；非空时不报警也不静默', max_length=32, verbose_name='失败原因')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('notified', models.BooleanField(default=False, verbose_name='已通知')),
                ('dismissed_as_false', models.BooleanField(default=False, help_text='用户手动标记为误报；触发后续 N 条同状态静默', verbose_name='用户标记误报')),
                ('auto_silenced', models.BooleanField(default=False, help_text='因前一条同状态被标误报，本次触发被静默（不报警）', verbose_name='被静默')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlm_states', to='streaming.camera')),
                ('prompt_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_states', to='vlm.vlmpromptconfig')),
            ],
            options={
                'verbose_name': 'VLM 检查记录',
                'verbose_name_plural': 'VLM 检查记录',
                'db_table': 'vlm_check_state',
                'ordering': ['-id'],
            },
        ),
    ]
