# Generated by Django 5.1.15 on 2026-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlmpromptconfig',
            name='max_tokens',
            field=models.IntegerField(default=256, help_text='VLM 单次回答最大 token 数（默认 256 覆盖状态描述）', verbose_name='VLM max_tokens'),
        ),
    ]
