# Generated by Django 5.1.15 on 2026-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0002_vlmpromptconfig_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlmpromptconfig',
            name='kind',
            field=models.CharField(choices=[('judge', '判断（命中报警）'), ('describe', '描述（状态跟踪）')], default='judge', help_text='judge=判断型（命中报警）；describe=描述型（状态跟踪）', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='vlmpromptconfig',
            name='max_tokens',
            field=models.IntegerField(default=512, help_text='VLM 单次回答最大 token 数（默认 512 覆盖状态描述；判断型可调小，描述型可调大）', verbose_name='VLM max_tokens'),
        ),
    ]
