# Generated by Django 5.1.15 on 2026-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0003_vlmpromptconfig_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlmcheckstate',
            name='status',
            field=models.TextField(blank=True, default='', help_text='判断型：首字符后剩余描述（短）；描述型：VLM 全文（可能长）。判断型的 status 用于静默签名 (cam, prompt, status)。', verbose_name='状态描述'),
        ),
    ]
