# Generated by Django 5.1.15 on 2026-09-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_camera_name'),
        ('vlm', '0004_alter_vlmcheckstate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlmcheckstate',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlm_states', to='streaming.camera'),
        ),
    ]
