# Generated by Django 5.1.15 on 2026-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0005_alter_vlmcheckstate_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='别名')),
                ('kind', models.CharField(choices=[('mobile_app', '手机通知（HA mobile_app）'), ('speaker', '音箱播报（HA text.set_value）')], max_length=16, verbose_name='类型')),
                ('target_id', models.CharField(help_text='mobile_app 填 notify.mobile_app_xxx；speaker 填 text.xiaomi_xxx', max_length=128, verbose_name='HA 服务/实体 ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知目标',
                'verbose_name_plural': '通知目标',
                'db_table': 'vlm_notify_target',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='vlmpromptconfig',
            name='notify_on_hit',
            field=models.BooleanField(default=True, help_text='总开关。关闭后即使配了 notify_targets 也不发通知。', verbose_name='命中时通知（总开关）'),
        ),
        migrations.AddField(
            model_name='vlmpromptconfig',
            name='notify_targets',
            field=models.ManyToManyField(blank=True, help_text='命中时要通知的目标；空 = 不通知。与 notify_on_hit AND 关系。', related_name='prompts', to='vlm.notifytarget', verbose_name='通知目标'),
        ),
    ]
