# Generated by Django 5.1.15 on 2026-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0006_notifytarget_alter_vlmpromptconfig_notify_on_hit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlmcheckstate',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('timeout', '超时'), ('network_error', '网络错误'), ('parse_error', '解析错误'), ('no_baby', '窗口内无 baby'), ('manual_paused', '已被手动暂停'), ('out_of_window', '窗口已被 FrameQueue 淘汰'), ('startup_failed', 'llama-server 启失败')], default='', help_text='VLM 调用失败原因；非空时不报警也不静默', max_length=32, verbose_name='失败原因'),
        ),
    ]
