# Generated by Django 5.1.15 on 2026-09-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_camera_name'),
        ('vlm', '0007_alter_vlmcheckstate_failure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLMQueuedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_list', models.JSONField(default=list, help_text='窗口内所有 ts（int 列表，按时间升序；window_start = ts_list[0]）', verbose_name='窗口 ts 列表')),
                ('window_sec', models.IntegerField(verbose_name='窗口长度')),
                ('img1', models.CharField(blank=True, default='', max_length=512, verbose_name='最早帧路径')),
                ('img2', models.CharField(blank=True, default='', max_length=512, verbose_name='中间帧路径')),
                ('img3', models.CharField(blank=True, default='', max_length=512, verbose_name='最晚帧路径')),
                ('img1_ts', models.IntegerField(blank=True, null=True, verbose_name='最早帧 ts')),
                ('img2_ts', models.IntegerField(blank=True, null=True, verbose_name='中间帧 ts')),
                ('img3_ts', models.IntegerField(blank=True, null=True, verbose_name='最晚帧 ts')),
                ('has_baby_in_window', models.BooleanField(default=False, verbose_name='窗口内有 baby')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('done', '已完成'), ('failed', '失败（超过重试上限）')], default='pending', help_text='pending=待处理；done=Drainer 已完成；failed=超过重试上限放弃', max_length=16, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='已重试次数')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入队时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlm_queued_tasks', to='streaming.camera')),
                ('prompt_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_tasks', to='vlm.vlmpromptconfig')),
            ],
            options={
                'verbose_name': 'VLM 队列任务',
                'verbose_name_plural': 'VLM 队列任务',
                'db_table': 'vlm_queued_task',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='vlmqueued_status_created_idx')],
            },
        ),
    ]
