# Generated by Django 5.1.15 on 2026-09-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlm', '0014_switch_notify_targets_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlmpromptconfig',
            name='notify_body_template',
            field=models.CharField(blank=True, default='', help_text='留空 = 默认「{cam} 在 {time} 检出（{status}）」。同一份文案用于手机正文与音箱播报；{status} 为空时，它外面那对括号会一起省略（不再出现「未提供状态」）。', max_length=255, verbose_name='通知正文模板'),
        ),
        migrations.AddField(
            model_name='vlmpromptconfig',
            name='notify_title_template',
            field=models.CharField(blank=True, default='', help_text='留空 = 默认「【宝宝告警·{prompt}】」（手机通知的标题）。占位符：{prompt} 检查项名 / {cam} 摄像头 / {time} 时间 / {status} VLM 回答的状态', max_length=128, verbose_name='通知标题模板'),
        ),
    ]
