# Generated by Django 5.1.15 on 2026-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMHealthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('vlm', 'VLM 视觉（:8082）'), ('asr', 'ASR 音频描述（:8136）')], max_length=16, unique=True, verbose_name='服务')),
                ('state', models.CharField(choices=[('closed', '正常'), ('open', '熔断中'), ('half_open', '探测中')], default='closed', max_length=16, verbose_name='熔断状态')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续连接失败次数')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次失败')),
                ('last_probe_at', models.DateTimeField(blank=True, help_text='半开态放出的那条探测请求的发出时间。', null=True, verbose_name='最近一次探测发出')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次成功')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM 服务熔断状态',
                'verbose_name_plural': 'LLM 服务熔断状态',
            },
        ),
    ]
