# Generated by Django 5.1.15 on 2026-09-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streaming', '0004_default_best_baby'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disabled', '已禁用'), ('initializing', '初始化中'), ('ready', '采集中'), ('no_audio_profile', '无音频轨'), ('capture_error', '采集异常'), ('model_error', '模型异常'), ('degraded', '降级运行'), ('stopped', '已停止')], default='disabled', max_length=32, verbose_name='状态')),
                ('last_packet_at', models.DateTimeField(blank=True, null=True, verbose_name='最近收到音频')),
                ('coverage_ok_from_ts', models.BigIntegerField(default=0, help_text='从该时刻起音频采集持续正常、中间没断过；用于覆盖完整性判定。', verbose_name='覆盖正常起点(epoch秒)')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('yamnet_version', models.CharField(blank=True, default='', max_length=64, verbose_name='YAMNet 版本')),
                ('panns_version', models.CharField(blank=True, default='', max_length=64, verbose_name='PANNs 版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_runtime_state', to='streaming.camera', verbose_name='摄像头')),
            ],
            options={
                'verbose_name': '音频运行状态',
                'verbose_name_plural': '音频运行状态',
                'db_table': 'vlm_audio_runtime_state',
            },
        ),
    ]
