# Generated by Django 5.1.15 on 2026-09-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_detect', '0001_initial'),
        ('streaming', '0004_default_best_baby'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start_ts', models.BigIntegerField(verbose_name='窗口开始(epoch秒)')),
                ('window_end_ts', models.BigIntegerField(verbose_name='窗口结束(epoch秒)')),
                ('yamnet_payload', models.JSONField(blank=True, default=dict, verbose_name='YAMNet 输出')),
                ('panns_payload', models.JSONField(blank=True, default=dict, verbose_name='PANNs 输出')),
                ('consensus_payload', models.JSONField(blank=True, default=dict, verbose_name='共识结果')),
                ('decision', models.CharField(choices=[('positive', '共识阳性'), ('negative', '非阳性'), ('degraded', '降级')], default='negative', help_text='多标签时：任一标签 positive → positive。', max_length=16, verbose_name='窗口决策')),
                ('log_reason', models.CharField(blank=True, choices=[('positive', '共识阳性'), ('near_threshold', '近阈值'), ('state_change', '状态变化')], default='', max_length=24, verbose_name='落库原因')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
                ('camera', models.ForeignKey(blank=True, help_text='摄像头删除后保留日志（spec §5.1）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_detection_logs', to='streaming.camera', verbose_name='摄像头')),
            ],
            options={
                'verbose_name': '声音检测日志',
                'verbose_name_plural': '声音检测日志',
                'db_table': 'vlm_sound_detection_log',
                'ordering': ['-window_end_ts', '-id'],
                'indexes': [models.Index(fields=['camera', 'window_end_ts'], name='vlm_sdl_cam_end_idx'), models.Index(fields=['camera', 'created_at'], name='vlm_sdl_cam_created_idx')],
            },
        ),
    ]
