# Generated by Django 5.1.15 on 2026-09-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_detect', '0002_sounddetectionlog'),
        ('streaming', '0004_default_best_baby'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recording', '录制中'), ('pending_description', '待描述'), ('describing', '描述中'), ('completed', '已完成'), ('failed', '失败')], default='recording', max_length=24, verbose_name='事件状态')),
                ('started_at_ts', models.BigIntegerField(verbose_name='事件开始(epoch秒)')),
                ('ended_at_ts', models.BigIntegerField(blank=True, help_text='事件关闭时回填；= 最后一个阳性窗结束 + 后录 3s。', null=True, verbose_name='事件结束(epoch秒)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始(展示用)')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束(展示用)')),
                ('duration_sec', models.FloatField(default=0.0, verbose_name='录音时长(秒)')),
                ('audio_path', models.CharField(blank=True, default='', help_text='与 VLMCheckState.img1/2/3 约定一致，存绝对路径不存 URL。', max_length=512, verbose_name='音频文件绝对路径')),
                ('audio_format', models.CharField(default='flac', max_length=8, verbose_name='音频格式')),
                ('detected_labels', models.JSONField(blank=True, default=dict, verbose_name='检测标签及时间线')),
                ('silence_ranges', models.JSONField(blank=True, default=list, verbose_name='静音区间')),
                ('degraded', models.BooleanField(default=False, help_text='事件期间发生采集中断/模型异常（capture_gap），非静音结束。', verbose_name='降级标记')),
                ('recording_lead_sec', models.FloatField(default=0.0, help_text='录音起点比事件起点早多少秒；事件内偏移 = 录音内偏移 - 该值。', verbose_name='录音前导(秒)')),
                ('description_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='描述状态')),
                ('description_json', models.JSONField(blank=True, default=dict, verbose_name='结构化描述')),
                ('description_raw', models.TextField(blank=True, default='', verbose_name='4B 原始返回')),
                ('moss_model', models.CharField(blank=True, default='', max_length=64, verbose_name='描述模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera', models.ForeignKey(blank=True, help_text='摄像头删除后保留事件（spec §5.2）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_events', to='streaming.camera', verbose_name='摄像头')),
            ],
            options={
                'verbose_name': '音频事件',
                'verbose_name_plural': '音频事件',
                'db_table': 'vlm_audio_event',
                'ordering': ['-started_at_ts', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AudioEventSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='片段序号')),
                ('start_offset', models.FloatField(help_text='相对事件 started_at_ts。', verbose_name='起点偏移(秒)')),
                ('end_offset', models.FloatField(verbose_name='终点偏移(秒)')),
                ('audio_path', models.CharField(blank=True, default='', help_text='FLAC 落盘；请求 4B 前在内存转 WAV，不落中间文件。', max_length=512, verbose_name='分段音频绝对路径')),
                ('has_silence_before', models.BooleanField(default=False, verbose_name='分段前有静音点')),
                ('description_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='描述状态')),
                ('description_json', models.JSONField(blank=True, default=dict, verbose_name='片段描述')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audio_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio_detect.audioevent', verbose_name='音频事件')),
            ],
            options={
                'verbose_name': '音频事件分段',
                'verbose_name_plural': '音频事件分段',
                'db_table': 'vlm_audio_event_segment',
                'ordering': ['audio_event', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='audioevent',
            index=models.Index(fields=['camera', 'started_at_ts'], name='vlm_ae_cam_start_idx'),
        ),
        migrations.AddIndex(
            model_name='audioevent',
            index=models.Index(fields=['camera', 'ended_at_ts'], name='vlm_ae_cam_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='audioeventsegment',
            constraint=models.UniqueConstraint(fields=('audio_event', 'sequence'), name='vlm_aes_event_seq_uq'),
        ),
    ]
