# Generated by Django 5.1.15 on 2026-09-12 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_detect', '0003_audioevent_audioeventsegment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioServiceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired', models.CharField(choices=[('on', '开启'), ('off', '关闭')], default='off', max_length=8, verbose_name='用户期望状态')),
                ('reason', models.CharField(blank=True, choices=[('manual', '用户手动'), ('autostart', '自动启动'), ('crash', '异常退出')], default='', max_length=16, verbose_name='最近变更来源')),
                ('pid', models.IntegerField(blank=True, help_text='非空 = 当前有活跃租约，释放时清空；心跳超时即可被接管。', null=True, verbose_name='worker PID')),
                ('worker_epoch', models.CharField(blank=True, db_index=True, default='', help_text='最近一次租约的 epoch；worker 每次接管时生成新的，释放时保留（供 recover 界定范围）。', max_length=32, verbose_name='活跃实例标识')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='worker 心跳刷新；超过心跳超时即判定旧实例已死/卡死，允许接管。', verbose_name='租约更新时间')),
            ],
            options={
                'verbose_name': '音频服务状态',
                'verbose_name_plural': '音频服务状态',
                'db_table': 'vlm_audio_service_state',
            },
        ),
        migrations.AddField(
            model_name='audioevent',
            name='worker_epoch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='产出该事件的 worker 租约 epoch；recover 据此限定回收范围。', max_length=32, verbose_name='产出实例'),
        ),
        migrations.AddField(
            model_name='audioeventsegment',
            name='worker_epoch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='产出该分段的 worker 租约 epoch；recover 据此限定回收范围。', max_length=32, verbose_name='产出实例'),
        ),
    ]
