# Generated by Django 5.1.15 on 2026-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YOLOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('file_path', models.CharField(help_text='绝对路径；或相对项目根 09_web_vlm_manage/ 的路径', max_length=512, verbose_name='.pt 路径')),
                ('class_names', models.JSONField(default=list, help_text="该 model 输出的目标类别列表（如 ['baby'] 或 ['person','cat']）；FrameItem 上对应 has_<name> 字段", verbose_name='覆盖类别')),
                ('coco_class_ids', models.JSONField(default=list, help_text='ultralytics predict(classes=...) 过滤参数；自定义模型（如 best.pt）填 []', verbose_name='COCO 类别 ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YOLO 模型',
                'verbose_name_plural': 'YOLO 模型',
                'db_table': 'yolo_model',
                'ordering': ['id'],
            },
        ),
    ]
