# Generated by Django 5.1.15 on 2026-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('source_type', models.CharField(choices=[('file', '视频文件'), ('onvif', 'ONVIF 摄像头')], default='file', max_length=16, verbose_name='源类型')),
                ('file_path', models.CharField(blank=True, default='', max_length=512, verbose_name='视频文件路径（绝对路径）')),
                ('onvif_host', models.CharField(blank=True, default='', max_length=128, verbose_name='ONVIF 主机')),
                ('onvif_port', models.PositiveIntegerField(default=80, verbose_name='ONVIF 端口')),
                ('onvif_username', models.CharField(blank=True, default='', max_length=64, verbose_name='ONVIF 用户名')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'db_table': 'vlm_camera',
                'ordering': ['id'],
            },
        ),
    ]
