# Generated by Django 5.1.15 on 2026-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_camera_name'),
        ('yolo_detect', '0002_seed_yolomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='yolo_models',
            field=models.ManyToManyField(blank=True, help_text='该摄像头启用的 YOLO 模型；空 = 不识别。改了会通过 m2m_changed signal 通知 YoloLoop 刷新缓存。', related_name='cameras', to='yolo_detect.yolomodel', verbose_name='YOLO 模型'),
        ),
    ]
